apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: targetgroupcontroller
spec:
  selector:
    matchLabels:
      app: targetgroupcontroller
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: targetgroupcontroller
    spec:
      serviceAccountName: targetgroupcontroller
      containers:
      - name: targetgroupcontroller 
        image: gauntletwizard/targetgroupcontroller
        args: ["--region=us-east-1", "--service=", "--port=9000", "--targetgrouparn=arn:aws:elasticloadbalancing:"]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-targetgroupcontroller
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-targetgroupcontroller
              key: AWS_SECRET_ACCESS_KEY
        ports:
        - containerPort: 8080
