apiVersion: v1
kind: ServiceAccount
metadata:
  name: targetgroupcontroller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: targetgroupcontroller
  name: targetgroupcontroller-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: targetgroupcontroller-role
subjects:
- kind: ServiceAccount
  name: targetgroupcontroller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: targetgroupcontroller
  name: targetgroupcontroller-role
rules:
- apiGroups: [""]
  resources: ["endpoints",""]
  verbs: ["get", "list", "watch"]
