apiVersion: v1
kind: Service
metadata:
  name: targetgroupcontroller 
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 8080
  selector:
    app: targetgroupcontroller
  type: ClusterIP
